version: '3'

services:

  db:
    image: postgres:9.6
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-app_development}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-xxx}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-xxx}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}
    volumes:
      - ./rails:/app

  web:
    build: docker/web
    depends_on:
      - app
    ports:
      - '80:80'
    volumes:
      - ./rails:/app

  cron:
    build: docker/cron
    depends_on:
      - db
    volumes:
      - ./backup:/backup
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-app_development}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-xxx}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-xxx}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}

volumes:
  db_data:
