version: '3'

services:

  db:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./rails:/app
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
#    ports:
#      - '3000:3000'
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_NAME=app_development
      - DB_USERNAME=postgres
      - DB_PASSWORD=

  web:
    build: docker/web
    volumes:
      - ./rails:/app
    depends_on:
      - app
    ports:
      - '80:80'

volumes:
  db_data:
