version: '3'

services:

  db:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    expose:
      - '3000'
    environment:
      - TZ=Asia/Tokyo
      - NODE_ENV=${NODE_ENV:-development}
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-app_development}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-xxx}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-xxx}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./rails:/app

  web:
    build: docker/web
    depends_on:
      - app
    environment:
      - TZ=Asia/Tokyo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    expose:
      - '80'
    volumes:
      - ./rails:/app

  https-portal:
    image: steveltn/https-portal:1
    depends_on:
      - web
    environment:
      DOMAINS: 'landism.local -> http://web:80'
      STAGE: 'local'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./ssl-certs:/var/lib/https-portal

  cron:
    build: docker/cron
    depends_on:
      - db
    environment:
      - TZ=Asia/Tokyo
      - RAILS_ENV=${RAILS_ENV:-development}
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-app_development}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-xxx}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-xxx}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}
      - S3_BUCKET=${S3_BUCKET:-landin-test}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./backup:/backup

volumes:
  db_data:
