version: '3'

services:

  db:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    expose:
      - '3000'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - .:/app

  web:
    build: docker/web
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - .:/app

  cron:
    build: docker/cron
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./backup:/backup

volumes:
  db_data:
