version: '3'

services:

  db:
    env_file:
      - production.env
    expose:
      - '5432'
    restart: always

  app:
    env_file:
      - production.env
    environment:
      - RAILS_LOG_TO_STDOUT=TRUE
    restart: always

  web:
    env_file:
      - production.env
    expose:
      - '80'
    restart: always

  https-portal:
    image: steveltn/https-portal:1
    depends_on:
      - web
    env_file:
      - production.env
    environment:
      DOMAINS: "${APP_HOST} -> http://web:80"
      STAGE: 'production'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - ./ssl-certs:/var/lib/https-portal


  cron:
    env_file:
      - production.env
    restart: always
