version: '3'

services:

  db:
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - development.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  rails:
    build:
      context: rails
      dockerfile: .devcontainer/Dockerfile
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    expose:
      - '3000'
    env_file:
      - development.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./rails:/app

  nginx:
    build: nginx
    depends_on:
      - rails
    env_file:
      - development.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    expose:
      - '80'
    volumes:
      - ./rails:/app

  https-portal:
    image: steveltn/https-portal:1
    depends_on:
      - nginx
    environment:
      DOMAINS: "${APP_HOST:-localhost} -> http://nginx:80"
      STAGE: 'local'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./ssl-certs:/var/lib/https-portal

  cron:
    build: cron
    depends_on:
      - db
    env_file:
      - development.env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    volumes:
      - ./backup:/backup

volumes:
  db_data:
