version: '3'

services:

  db:
    image: postgres:9.6
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    env_file:
      - docker/development.env
    volumes:
      - ./rails:/app

  web:
    build: docker/web
    depends_on:
      - app
    ports:
      - '80:80'
    volumes:
      - ./rails:/app

  cron:
    build: docker/cron
    depends_on:
      - db
    volumes:
      - ./backup:/backup
    env_file:
      - docker/development.env

volumes:
  db_data:
