version: '3'

services:

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
#    image: postgres:9.3
    ports:
    - '5432:5432'

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
    - .:/rollbook
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
    - '3000:3000'
    depends_on:
    - db
    environment:
    - DB_USERNAME=postgres
    - DB_PASSWORD=

