# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d42a3713899dc1ada082d1333da63c77457235752e9eae86f7296178ee1db298c7ae412ab6711c91a4334290adf936d1d0abdd5512f6a9fca85350bf1b0e933c

test:
  secret_key_base: 5dcb135af927e02a19fea94503b6700e329c684550b4f5dd6c26c6334a76f7ae6e62dc9de30c9fd0d10694bd7dc7d34889357b505b93fa2e75d51743a6e4364f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
