development:
  adapter: postgresql
  encoding: unicode
  database: rollbook_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: rollbook_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: rollbook_production
  pool: 5
  username: rollbook
  password:
