require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AgeGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # AgeGroup. As you add validations to AgeGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AgeGroupsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all age_groups as @age_groups" do
      age_group = AgeGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:age_groups).should eq([age_group])
    end
  end

  describe "GET show" do
    it "assigns the requested age_group as @age_group" do
      age_group = AgeGroup.create! valid_attributes
      get :show, {:id => age_group.to_param}, valid_session
      assigns(:age_group).should eq(age_group)
    end
  end

  describe "GET new" do
    it "assigns a new age_group as @age_group" do
      get :new, {}, valid_session
      assigns(:age_group).should be_a_new(AgeGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested age_group as @age_group" do
      age_group = AgeGroup.create! valid_attributes
      get :edit, {:id => age_group.to_param}, valid_session
      assigns(:age_group).should eq(age_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AgeGroup" do
        expect {
          post :create, {:age_group => valid_attributes}, valid_session
        }.to change(AgeGroup, :count).by(1)
      end

      it "assigns a newly created age_group as @age_group" do
        post :create, {:age_group => valid_attributes}, valid_session
        assigns(:age_group).should be_a(AgeGroup)
        assigns(:age_group).should be_persisted
      end

      it "redirects to the created age_group" do
        post :create, {:age_group => valid_attributes}, valid_session
        response.should redirect_to(AgeGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved age_group as @age_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        AgeGroup.any_instance.stub(:save).and_return(false)
        post :create, {:age_group => { "name" => "invalid value" }}, valid_session
        assigns(:age_group).should be_a_new(AgeGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AgeGroup.any_instance.stub(:save).and_return(false)
        post :create, {:age_group => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested age_group" do
        age_group = AgeGroup.create! valid_attributes
        # Assuming there are no other age_groups in the database, this
        # specifies that the AgeGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AgeGroup.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => age_group.to_param, :age_group => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested age_group as @age_group" do
        age_group = AgeGroup.create! valid_attributes
        put :update, {:id => age_group.to_param, :age_group => valid_attributes}, valid_session
        assigns(:age_group).should eq(age_group)
      end

      it "redirects to the age_group" do
        age_group = AgeGroup.create! valid_attributes
        put :update, {:id => age_group.to_param, :age_group => valid_attributes}, valid_session
        response.should redirect_to(age_group)
      end
    end

    describe "with invalid params" do
      it "assigns the age_group as @age_group" do
        age_group = AgeGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AgeGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => age_group.to_param, :age_group => { "name" => "invalid value" }}, valid_session
        assigns(:age_group).should eq(age_group)
      end

      it "re-renders the 'edit' template" do
        age_group = AgeGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AgeGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => age_group.to_param, :age_group => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested age_group" do
      age_group = AgeGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => age_group.to_param}, valid_session
      }.to change(AgeGroup, :count).by(-1)
    end

    it "redirects to the age_groups list" do
      age_group = AgeGroup.create! valid_attributes
      delete :destroy, {:id => age_group.to_param}, valid_session
      response.should redirect_to(age_groups_url)
    end
  end

end
