require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MembersCoursesController do

  # This should return the minimal set of attributes required to create a valid
  # MembersCourse. As you add validations to MembersCourse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "member_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MembersCoursesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all members_courses as @members_courses" do
      members_course = MembersCourse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:members_courses).should eq([members_course])
    end
  end

  describe "GET show" do
    it "assigns the requested members_course as @members_course" do
      members_course = MembersCourse.create! valid_attributes
      get :show, {:id => members_course.to_param}, valid_session
      assigns(:members_course).should eq(members_course)
    end
  end

  describe "GET new" do
    it "assigns a new members_course as @members_course" do
      get :new, {}, valid_session
      assigns(:members_course).should be_a_new(MembersCourse)
    end
  end

  describe "GET edit" do
    it "assigns the requested members_course as @members_course" do
      members_course = MembersCourse.create! valid_attributes
      get :edit, {:id => members_course.to_param}, valid_session
      assigns(:members_course).should eq(members_course)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MembersCourse" do
        expect {
          post :create, {:members_course => valid_attributes}, valid_session
        }.to change(MembersCourse, :count).by(1)
      end

      it "assigns a newly created members_course as @members_course" do
        post :create, {:members_course => valid_attributes}, valid_session
        assigns(:members_course).should be_a(MembersCourse)
        assigns(:members_course).should be_persisted
      end

      it "redirects to the created members_course" do
        post :create, {:members_course => valid_attributes}, valid_session
        response.should redirect_to(MembersCourse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved members_course as @members_course" do
        # Trigger the behavior that occurs when invalid params are submitted
        MembersCourse.any_instance.stub(:save).and_return(false)
        post :create, {:members_course => { "member_id" => "invalid value" }}, valid_session
        assigns(:members_course).should be_a_new(MembersCourse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MembersCourse.any_instance.stub(:save).and_return(false)
        post :create, {:members_course => { "member_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested members_course" do
        members_course = MembersCourse.create! valid_attributes
        # Assuming there are no other members_courses in the database, this
        # specifies that the MembersCourse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MembersCourse.any_instance.should_receive(:update).with({ "member_id" => "1" })
        put :update, {:id => members_course.to_param, :members_course => { "member_id" => "1" }}, valid_session
      end

      it "assigns the requested members_course as @members_course" do
        members_course = MembersCourse.create! valid_attributes
        put :update, {:id => members_course.to_param, :members_course => valid_attributes}, valid_session
        assigns(:members_course).should eq(members_course)
      end

      it "redirects to the members_course" do
        members_course = MembersCourse.create! valid_attributes
        put :update, {:id => members_course.to_param, :members_course => valid_attributes}, valid_session
        response.should redirect_to(members_course)
      end
    end

    describe "with invalid params" do
      it "assigns the members_course as @members_course" do
        members_course = MembersCourse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MembersCourse.any_instance.stub(:save).and_return(false)
        put :update, {:id => members_course.to_param, :members_course => { "member_id" => "invalid value" }}, valid_session
        assigns(:members_course).should eq(members_course)
      end

      it "re-renders the 'edit' template" do
        members_course = MembersCourse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MembersCourse.any_instance.stub(:save).and_return(false)
        put :update, {:id => members_course.to_param, :members_course => { "member_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested members_course" do
      members_course = MembersCourse.create! valid_attributes
      expect {
        delete :destroy, {:id => members_course.to_param}, valid_session
      }.to change(MembersCourse, :count).by(-1)
    end

    it "redirects to the members_courses list" do
      members_course = MembersCourse.create! valid_attributes
      delete :destroy, {:id => members_course.to_param}, valid_session
      response.should redirect_to(members_courses_url)
    end
  end

end
