require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecessesController do

  # This should return the minimal set of attributes required to create a valid
  # Recess. As you add validations to Recess, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "members_course_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecessesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all recesses as @recesses" do
      recess = Recess.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recesses).should eq([recess])
    end
  end

  describe "GET show" do
    it "assigns the requested recess as @recess" do
      recess = Recess.create! valid_attributes
      get :show, {:id => recess.to_param}, valid_session
      assigns(:recess).should eq(recess)
    end
  end

  describe "GET new" do
    it "assigns a new recess as @recess" do
      get :new, {}, valid_session
      assigns(:recess).should be_a_new(Recess)
    end
  end

  describe "GET edit" do
    it "assigns the requested recess as @recess" do
      recess = Recess.create! valid_attributes
      get :edit, {:id => recess.to_param}, valid_session
      assigns(:recess).should eq(recess)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Recess" do
        expect {
          post :create, {:recess => valid_attributes}, valid_session
        }.to change(Recess, :count).by(1)
      end

      it "assigns a newly created recess as @recess" do
        post :create, {:recess => valid_attributes}, valid_session
        assigns(:recess).should be_a(Recess)
        assigns(:recess).should be_persisted
      end

      it "redirects to the created recess" do
        post :create, {:recess => valid_attributes}, valid_session
        response.should redirect_to(Recess.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recess as @recess" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recess.any_instance.stub(:save).and_return(false)
        post :create, {:recess => { "members_course_id" => "invalid value" }}, valid_session
        assigns(:recess).should be_a_new(Recess)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recess.any_instance.stub(:save).and_return(false)
        post :create, {:recess => { "members_course_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recess" do
        recess = Recess.create! valid_attributes
        # Assuming there are no other recesses in the database, this
        # specifies that the Recess created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Recess.any_instance.should_receive(:update).with({ "members_course_id" => "1" })
        put :update, {:id => recess.to_param, :recess => { "members_course_id" => "1" }}, valid_session
      end

      it "assigns the requested recess as @recess" do
        recess = Recess.create! valid_attributes
        put :update, {:id => recess.to_param, :recess => valid_attributes}, valid_session
        assigns(:recess).should eq(recess)
      end

      it "redirects to the recess" do
        recess = Recess.create! valid_attributes
        put :update, {:id => recess.to_param, :recess => valid_attributes}, valid_session
        response.should redirect_to(recess)
      end
    end

    describe "with invalid params" do
      it "assigns the recess as @recess" do
        recess = Recess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recess.any_instance.stub(:save).and_return(false)
        put :update, {:id => recess.to_param, :recess => { "members_course_id" => "invalid value" }}, valid_session
        assigns(:recess).should eq(recess)
      end

      it "re-renders the 'edit' template" do
        recess = Recess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recess.any_instance.stub(:save).and_return(false)
        put :update, {:id => recess.to_param, :recess => { "members_course_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recess" do
      recess = Recess.create! valid_attributes
      expect {
        delete :destroy, {:id => recess.to_param}, valid_session
      }.to change(Recess, :count).by(-1)
    end

    it "redirects to the recesses list" do
      recess = Recess.create! valid_attributes
      delete :destroy, {:id => recess.to_param}, valid_session
      response.should redirect_to(recesses_url)
    end
  end

end
