source 'https://rubygems.org'

gem 'rails', '5.1.6.2'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
# ページ
gem 'kaminari'
# コーディング
gem 'annotate'
# View Model
gem 'draper'
gem 'bootsnap'
gem 'puma'

# group :doc do
#   gem 'sdoc', require: false
# end

# API
gem 'aws-sdk-cognitoidentityprovider'
gem 'fast_jsonapi'
gem 'jwt'
gem 'rack-cors', require: 'rack/cors'

group :development do
  gem 'brakeman', require: false
  gem 'bullet'
  gem 'license_finder'
  gem 'listen'
  gem 'pry'
  gem 'pry-rails'
  gem 'rails_best_practices', require: false
  gem 'rubocop', require: false
  gem 'spring'
  gem 'spring-watcher-listen'
end

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'debase'
  # gem 'factory_bot_rails'
  # gem 'faker'
  gem 'fog-local'
  gem 'fuubar'
  gem 'rspec-rails'
  gem 'ruby-debug-ide'
end

group :test do
  # gem 'capybara'
  gem 'database_cleaner'
end

# CSS
gem 'bootstrap-sass'
gem 'bootstrap-datepicker-rails'
gem 'font-awesome-rails'
# チャート
gem 'lazy_high_charts'
# 認証
gem 'devise'
# 検索
gem 'ransack'
# PDF
gem 'wkhtmltopdf-binary'
gem 'wicked_pdf'
# 監視
# gem 'newrelic_rpm'
# パン屑
gem 'gretel'

gem 'exception_notification'
gem 'slack-notifier'
