on:
  push:
    branches:
      - "**"

jobs:
  rubyclitic:
    runs-on: ubuntu-16.04
    # container:
    #   image: ruby:2.5.5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: run rubycritic
        run: |
          gem install rubycritic
          rubycritic
      - name: Archive report
        uses: actions/upload-artifact@v1
        with:
          name: rubycritic-report
          path: tmp/rubycritic
