on:
  push:
    branches:
      - "**"

jobs:
  rubyclitic:
    runs-on: ubuntu-16.04
    # container:
    #   image: ruby:2.5.5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Run rubycritic
        run: |
          gem install rubycritic
          rubycritic
      - name: Archive report
        uses: actions/upload-artifact@v1
        with:
          name: rubycritic
          path: tmp/rubycritic
      - name: Run rails_best_practices
        run: |
          gem install rails_best_practices
          rails_best_practices -f html
      - name: Archive report
        uses: actions/upload-artifact@v1
        with:
          name: rails_best_practices
          path: rails_best_practices_output.html
