on:
  push:
    branches:
      - "**"

jobs:
  rubyclitic:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.5
      - run: |
        gem install rubycritic
